#language: es


Característica: Como usuario deseo verificar del modulo "Alerts, Frame y Windows" la funcionalidad "Browser Windows"
  @TestAlerts
  Escenario: Como usuario en el modulo Alerts, frame y windows deseo comprobar la funcionalidad del boton Small modal
    Dado que como usuario del modulo Alerts, frame y windows
    Cuando selecciono el boton Small modal
    Entonces verifico los mensajes en los alerts


  Escenario: Como usuario en el modulo Alerts, frame y windows deseo comprobar la funcionalidad del boton Large modal
    Dado que como usuario del modulo Alerts, frame y windows
    Cuando selecciono el boton Large modal
    Entonces verifico los mensajes en los alerts

